### ISSUE TITLE
Should work just like `ls` command

### ISSUE THREAD

**Issue by TylerYang** [jShi-git/imgls#2]
Seems for now it will show all the files in a directory recursively, and I think it will be better to work just like `ls` command.

**Comment by jShi-git** [comment]
You can use it just almost like `ls`
`imgls dirname`
`imgls *.png`
in this shell has set the list style as `ls -l`，so the list style just `ls -l`,if you're talking about the list style

**Comment by TylerYang** [comment]
No, what I mean `recursively` is it will list all the files under its subfolder, 
let's say we have folder `A` 

```
-A
  -file1
  -file2
  -img3
  -subfolder1
      -subfile1
      -subfile2
      -subfile3
```

If I run `imgls` in folder A, it will show the file list, **including subfile1, subfile2, subfile3**

**Comment by jShi-git** [comment]
thanks for your advise，in imgls@1.0.4 i removed the directory recursively, you can update your imgls

**Comment by TylerYang** [comment]
@jShi-git :smiling_imp:

**Comment by jShi-git** [comment]
@TylerYang 中国人?搞得那么辛苦写英语😓

**Comment by TylerYang** [comment]
才注意到都是中国人， :sweat:
